### ISSUE TITLE
Single node is not parsed

### ISSUE THREAD

**Issue by tmcw** [aaronlidman/osm-and-geojson#6]
```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="OpenStreetMap server" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
  <node id="2451704701" version="2" changeset="17750354" lat="5.957788" lon="116.0706755" user="BernardLiew" uid="1728406" visible="true" timestamp="2013-09-09T13:34:57Z"/>
</osm>
```

results in a zero-length feature collection

**Comment by aaronlidman** [comment]
Sorry for the delay, I missed these notifications.

The node isn't showing up because it doesn't have any tags. Nodes without tags are classified as 'coords' used for building geometry and not output on their own, they're kept separate from tagged nodes. I got this from imposm.parser which makes the same distinction. The simplest solution would be to just output all nodes as their own geometry, but for a vast majority of cases this would greatly increase the number of items unnecessarily. The trade off I've gone with is to keep track of nodes used by other geometry and output anything unused at the end as its own geometry.

Anyway, it works now.

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Point",
        "coordinates": [
          116.0706755,
          5.957788
        ]
      },
      "type": "Feature",
      "properties": {}
    }
  ]
}
```
